name: deploy-functionApp

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            path: repo
        - uses: azure/log
          with:
             client-id: ${{secrets.AZURE_CLIENT_ID}} 
             tenant-id: ${{secrets.AZURE_TENANT_ID}}
             subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

